# Generated by Django 4.2.15 on 2025-03-16 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Q&A'), (2, '声明说明'), (3, '捐赠'), (4, '关于')], default=1, verbose_name='类型')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(max_length=512, verbose_name='内容')),
                ('dates', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('url', models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '信息通告',
                'db_table': 'everyday_about',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '获奖通告'), (2, '信息征集'), (3, '成员活动'), (4, '其他')], default=1, verbose_name='类型')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(max_length=512, verbose_name='内容')),
                ('dates', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('url', models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='链接')),
                ('is_show', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '新闻发布',
                'verbose_name_plural': '心理健康的新闻',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(max_length=1024, verbose_name='主体内容')),
                ('inner_web_url', models.CharField(blank=True, max_length=256, verbose_name='比赛官网')),
                ('addition_action_title', models.CharField(blank=True, max_length=256, verbose_name='附加活动标题')),
                ('addition_action_url', models.CharField(blank=True, max_length=256, verbose_name='附加活动地址')),
                ('background_color_1', models.CharField(default='default', max_length=24, verbose_name='弹窗背景色1')),
                ('background_color_2', models.CharField(default='default', max_length=24, verbose_name='弹窗背景色2')),
                ('background_color_3', models.CharField(default='default', max_length=24, verbose_name='弹窗背景色3')),
                ('is_show', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否展示')),
                ('is_important', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否紧急通知')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
            ],
            options={
                'verbose_name': '信息通知',
                'verbose_name_plural': '信息通告',
                'db_table': 'everyday_notices',
            },
        ),
    ]
