# Generated by Django 4.2.15 on 2025-03-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleanno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notices',
            options={'verbose_name': '通告展示', 'verbose_name_plural': '全体通告展示'},
        ),
    ]
