# Generated by Django 4.2.15 on 2025-03-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleanno', '0002_alter_notices_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
