# Generated by Django 4.2.15 on 2025-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleanno', '0003_about_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='color',
            field=models.CharField(default='#fff', max_length=64, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='about',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
