# Generated by Django 4.2.15 on 2025-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleanno', '0004_news_color_alter_about_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='color',
            field=models.CharField(default='#fff', max_length=64, verbose_name='颜色'),
        ),
    ]
