# Generated by Django 4.2.15 on 2025-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='姓名')),
                ('Account', models.CharField(max_length=32, verbose_name='账户')),
                ('PassWord', models.CharField(max_length=32, verbose_name='密码')),
                ('Email', models.CharField(max_length=36, verbose_name='邮箱')),
                ('Sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('Age', models.IntegerField(verbose_name='年龄')),
                ('WorkingCondition', models.IntegerField(choices=[(1, '未曾工作'), (2, '工作中'), (3, '待就业')], default=1, verbose_name='工作状态')),
                ('HealthGrade', models.IntegerField(choices=[(1, '优秀'), (2, '良好'), (3, '一般'), (4, '较差'), (5, '差')], default=3, verbose_name='健康等级')),
                ('Country', models.CharField(max_length=32, verbose_name='国家')),
                ('Token', models.CharField(blank=True, max_length=64, null=True, verbose_name='TOKEN')),
                ('PhoneNumber', models.CharField(max_length=32, verbose_name='手机号')),
                ('Address', models.CharField(max_length=40, verbose_name='地址')),
                ('LastLoginTime', models.DateField(verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户基本信息',
                'db_table': 'login_userinfo',
            },
        ),
    ]
