# Generated by Django 4.2.15 on 2025-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Country',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='LastLoginTime',
            field=models.DateField(blank=True, null=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号'),
        ),
    ]
