# Generated by Django 4.2.15 on 2025-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_userinfo_address_alter_userinfo_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='新闻类型')),
            ],
            options={
                'verbose_name': '新闻类型',
                'verbose_name_plural': '新闻类型',
                'db_table': 'news_type',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('Edit', models.CharField(default='张三', max_length=30, verbose_name='新闻编辑')),
                ('Time', models.DateField(verbose_name='时间')),
                ('Description', models.TextField(verbose_name='描述')),
                ('Memo', models.TextField(default='暂无', verbose_name='备注信息')),
                ('News', models.IntegerField(choices=[(1, '心理科普'), (3, '婚恋情感'), (2, '家庭关系'), (4, '人际社交'), (5, '自我觉察'), (6, '成长学习'), (7, '心理健康'), (8, '职场技能')], default=1, verbose_name='专业选择')),
            ],
            options={
                'verbose_name': '新闻报道',
                'verbose_name_plural': '新闻报道',
                'db_table': 'news_project',
            },
        ),
    ]
