# Generated by Django 4.2.15 on 2025-03-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_language_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='News',
            field=models.IntegerField(choices=[(1, '心理科普'), (2, '婚恋情感'), (3, '家庭关系'), (4, '人际社交'), (5, '自我觉察'), (6, '成长学习'), (7, '心理健康'), (8, '职场技能')], default=1, verbose_name='专业选择'),
        ),
    ]
