# Generated by Django 4.2.15 on 2025-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_project_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('testTitile', models.CharField(blank=True, max_length=640, null=True, verbose_name='题目')),
                ('testTime', models.DateTimeField(blank=True, null=True, verbose_name='测试时间')),
            ],
            options={
                'verbose_name': '快速测评',
                'verbose_name_plural': '快速测评题目集',
                'db_table': 'quick_assessment_db',
            },
        ),
        migrations.CreateModel(
            name='QuickAssessmentSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('randomQuestions', models.JSONField(verbose_name='所出题目')),
                ('selected', models.JSONField(default=list, verbose_name='选择的内容')),
                ('latestScore', models.IntegerField(blank=True, null=True, verbose_name='最终得分')),
                ('testTime', models.DateTimeField(blank=True, null=True, verbose_name='测试时间')),
            ],
            options={
                'verbose_name': '快评结果',
                'verbose_name_plural': '快评结果集',
                'db_table': 'quick_assessment_result_db',
            },
        ),
    ]
