# Generated by Django 4.2.15 on 2025-03-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_quickassessment_quickassessmentselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickassessment',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='下标'),
        ),
        migrations.AddField(
            model_name='quickassessment',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='下标'),
        ),
    ]
