# Generated by Django 4.2.15 on 2025-03-24 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_quickassessment_index_quickassessment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('705d7a0b-ff80-4856-917f-b93e1ba473f8'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessment',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='分数'),
        ),
    ]
