# Generated by Django 4.2.15 on 2025-03-24 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_quickassessmentselected_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickassessment',
            name='userId',
            field=models.CharField(default=uuid.UUID('e28a5185-6e8f-476c-843d-626100da44b3'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('0e6fb5b8-fe0a-4636-813a-c437edfcfbc0'), max_length=100, verbose_name='用户ID'),
        ),
    ]
