# Generated by Django 4.2.15 on 2025-03-29 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_quickassessment_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickassessment',
            name='userId',
            field=models.CharField(default=uuid.UUID('0fbec427-82f8-4f1c-9a54-7b215baef338'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='randomQuestions',
            field=models.JSONField(verbose_name='所选题目集'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('35c0846c-d6b2-4db4-a26f-5b4d2afd840f'), max_length=100, verbose_name='用户ID'),
        ),
    ]
