# Generated by Django 4.2.15 on 2025-03-29 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_quickassessment_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickassessment',
            name='userId',
            field=models.CharField(default=uuid.UUID('b1245d9f-f3bc-48b1-acd2-bc843e273027'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('d388a4b5-88b9-4e9d-88d8-54eb791c5600'), max_length=100, verbose_name='用户ID'),
        ),
    ]
