# Generated by Django 4.2.15 on 2025-03-29 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_quickassessment_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickassessment',
            name='userId',
            field=models.CharField(default=uuid.UUID('c2c5264f-233a-4347-a831-3a5667b4d0b6'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('20d2185e-7674-4ce3-a3d7-8d824bf052ab'), max_length=100, verbose_name='用户ID'),
        ),
    ]
