# Generated by Django 4.2.15 on 2025-03-29 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_quickassessment_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(default='快乐活着', max_length=128, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='quickassessment',
            name='userId',
            field=models.CharField(default=uuid.UUID('acac4bb4-036d-4bec-8425-eff55c6e34af'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('e6a246d7-8b19-48f3-8374-64e96e82cacc'), max_length=100, verbose_name='用户ID'),
        ),
    ]
