# Generated by Django 4.2.15 on 2025-04-05 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_userinfo_signature_alter_quickassessment_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickassessment',
            name='testType',
            field=models.IntegerField(default=1, null=True, verbose_name='测试类型'),
        ),
        migrations.AlterField(
            model_name='quickassessment',
            name='userId',
            field=models.CharField(default=uuid.UUID('03853baa-d7e5-4eb7-8f53-c9e84ec68675'), max_length=100, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='quickassessmentselected',
            name='userId',
            field=models.CharField(default=uuid.UUID('3cc98e1a-eebd-4c75-ab48-aa2d49126351'), max_length=100, verbose_name='用户ID'),
        ),
    ]
