# Generated by Django 4.2.15 on 2025-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiWithUserChatingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=40, verbose_name='话题名称')),
                ('TopicStartTime', models.TimeField(auto_now_add=True, verbose_name='话题开始时间')),
                ('TopicEndTime', models.TimeField(auto_now_add=True, verbose_name='话题结束时间')),
                ('KeyMan', models.TextField(max_length=50, verbose_name='关键人物')),
                ('TopicSummary', models.TextField(max_length=60, verbose_name='话题总结')),
                ('HealthScore', models.CharField(max_length=60, verbose_name='心理健康打分')),
                ('TopicSensitiveLevel', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级'), (5, '五级')], default=1, verbose_name='话题敏感度级别')),
                ('PredictivePsychology', models.IntegerField(choices=[(1, '优秀'), (2, '良好'), (3, '一般'), (4, '较差'), (5, '差')], default=3, verbose_name='健康等级')),
                ('Memo', models.TextField(default='...', max_length=512, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': 'AI聊天',
                'verbose_name_plural': '聊天',
                'db_table': 'ChattingWithAI',
            },
        ),
    ]
