# Generated by Django 4.2.15 on 2025-03-05 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiwithuserchatinginformation',
            options={'verbose_name': 'AI聊天', 'verbose_name_plural': 'AI聊天存储'},
        ),
        migrations.AlterField(
            model_name='aiwithuserchatinginformation',
            name='Memo',
            field=models.TextField(default='无', null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='aiwithuserchatinginformation',
            name='TopicEndTime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='话题结束时间'),
        ),
        migrations.AlterField(
            model_name='aiwithuserchatinginformation',
            name='TopicStartTime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='话题开始时间'),
        ),
    ]
