# Generated by Django 4.2.15 on 2025-03-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatmessage', '0002_alter_aiwithuserchatinginformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='traditionalAnsweringMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='题目内容')),
                ('index', models.IntegerField(default=0, verbose_name='题目序号')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '传统答题模式',
                'verbose_name_plural': '传统答题模式',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='题目')),
                ('choices', models.CharField(max_length=200, verbose_name='选项')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('experience', models.TextField(blank=True, max_length=500, null=True, verbose_name='心得体会')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '问题历史记录',
                'verbose_name_plural': '问题历史记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
