# Generated by Django 4.2.15 on 2025-03-14 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_language_project'),
        ('chatmessage', '0003_traditionalansweringmode_questionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='questionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_histories', to='info.userinfo', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='traditionalansweringmode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
