# Generated by Django 4.2.15 on 2025-03-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessage', '0004_alter_questionhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiwithuserchatinginformation',
            name='Content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiwithuserchatinginformation',
            name='Role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiwithuserchatinginformation',
            name='UserId',
            field=models.CharField(default='default_user', max_length=100),
        ),
    ]
