# Generated by Django 4.2.15 on 2025-03-17 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessage', '0005_aiwithuserchatinginformation_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='summaryAnswerStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(default='default_user', max_length=100)),
                ('Content', models.TextField()),
                ('ReturnTime', models.TimeField(default=django.utils.timezone.now, verbose_name='返回时间')),
                ('TopicSummary', models.TextField(max_length=60, verbose_name='话题总结')),
                ('HealthScore', models.CharField(max_length=60, verbose_name='心理健康打分')),
                ('Memo', models.TextField(default='无', null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '聊天列表反响',
                'verbose_name_plural': '聊天列表反响',
            },
        ),
    ]
