# Generated by Django 4.2.15 on 2025-03-18 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessage', '0006_summaryanswerstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryanswerstorage',
            name='Content',
            field=models.TextField(verbose_name='聊天内容'),
        ),
        migrations.AlterField(
            model_name='summaryanswerstorage',
            name='ReturnTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='返回时间'),
        ),
        migrations.AlterField(
            model_name='summaryanswerstorage',
            name='TopicSummary',
            field=models.TextField(max_length=1000, verbose_name='话题总结'),
        ),
        migrations.AlterField(
            model_name='summaryanswerstorage',
            name='UserId',
            field=models.CharField(default='default_user', max_length=100, verbose_name='用户ID'),
        ),
    ]
